name: example
description: Example app for form_builder_map_field package
homepage: https://github.com/danvick/form_builder_map_field/tree/master/example
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_form_builder: ^4.2.0
  form_builder_map_field:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: 0.17.0-nullsafety.2

flutter:
  uses-material-design: true
